nama: Demo GitHub Actions 
nama-jalan: ${{ github.actor }} sedang menguji GitHub Actions ğŸš€ 
pada: [push] 
pekerjaan: 
  Explore-GitHub-Actions: 
    runs-on: ubuntu-latest 
    langkah-langkah: 
      - jalankan: echo "ğŸ‰ Pekerjaan dipicu secara otomatis oleh peristiwa ${{ github.event_name }}." 
      - jalankan: echo "ğŸ§ Pekerjaan ini sekarang berjalan pada server ${{ runner.os }} yang dihosting oleh GitHub!" 
      - jalankan: echo "ğŸ” Nama cabang Anda adalah ${{ github.ref }} dan repositori Anda adalah ${{ github.repository }}." 
      - nama: Kode repositori Check out 
        menggunakan: actions/checkout@v4 
      - jalankan: echo "ğŸ’¡ Repositori ${{ github.repository }} telah dikloning ke runner." 
      - jalankan: echo "ğŸ–¥ï¸ Alur kerja sekarang siap untuk menguji kode Anda pada runner." 
      - nama: Daftar file dalam repositori 
        jalankan: | 
          ls ${{ github.workspace }} 
      - jalankan: echo "ğŸ Status pekerjaan ini adalah ${{ job.status }}."

